spring:
  application:
    name: paykids

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  #Database
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME} #[DB_USERNAME]
    password: ${DB_PASSWORD} #[DB_PASSWORD]
    driver-class-name: com.mysql.cj.jdbc.Driver #[JDBC DRIVER]

#Swagger
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true # 예쁘게
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger # 접속경로
    groups-order: DESC # 내림차순
    tags-sorter: alpha
    operations-sorter: method
    #alpha(알파벳 순 정렬), method(HTTP메소드 순)
    disable-swagger-default-url: true
    display-request-duration: true
  paths-to-match:
    - /**